version: "3.9"
services:
  kingdomino:
    image: marcpartensky/kingdomino
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DISPLAY: ${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri

